### ISSUE TITLE
Make the script available for www.plickers.com instead of juste plickers.com

### ISSUE THREAD

**Issue by triomen** [obook/TeXify-Plickers#1]
I just took one hour to figure out why the user script didn't work : it was because I used "www.plickers.com" instead of "plickers.com".
I saw that the user script was configured only for "plickers.com"

Maybe change https://github.com/obook/TeXify-Plickers/blob/master/user-script/TeXify-Plickers.user.js#L9 ?

**Comment by obook** [comment]
Hello.
Is fixed now, thank you.

**Comment by triomen** [comment]
Thanks !
